name: Testing GH Actions

on: [push]

jobs:
  checking-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: install bats
        run: npm i -g bats
      - run: bats -v
